<Project>
	<PropertyGroup Condition="'$(MSBuildProjectName)' == 'ComputeSharp' or '$(MSBuildProjectName)' == 'ComputeSharp.Core'">
		<BaseOutputPath>$(MSBuildProjectDirectory)\bin\CausticTransport\</BaseOutputPath>
		<BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\obj\CausticTransport\</BaseIntermediateOutputPath>
		<MSBuildProjectExtensionsPath>$(MSBuildProjectDirectory)\obj\</MSBuildProjectExtensionsPath>
		<DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)\obj\**</DefaultItemExcludes>
	</PropertyGroup>
	<PropertyGroup Condition="'$(MSBuildProjectName)' == 'ComputeSharp'">
		<AssemblyName>CausticTransport.ComputeSharp</AssemblyName>
	</PropertyGroup>
	<PropertyGroup Condition="'$(MSBuildProjectName)' == 'ComputeSharp.Core'">
		<AssemblyName>CausticTransport.ComputeSharp.Core</AssemblyName>
	</PropertyGroup>
</Project>
